name: Qualys Container Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  qualys-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write # Necessário para abrir/reabrir issues
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Build da imagem localmente para o scanner a encontrar
      # O Docker buscará um arquivo chamado "Dockerfile" na raiz
      - name: Build local image
        run: docker build -t poc-api-matias:latest .

      # 2. Execução do script de scan
      - name: Run Qualys Container Security Scan
        env:
          QUALYS_ACCESS_TOKEN: ${{ secrets.QUALYS_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUALYS_POD: US3
          IMAGE_NAME: poc-api-matias
          IMAGE_TAG: latest
          POLICY_TAGS: "POC_API_MATIAS"
        run: |
          # Garante permissão de execução e executa o script na raiz
          chmod +x ./qualys_container_scan.sh
          ./qualys_container_scan.sh
