name: Qualys Container Security Scan

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  qualys-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t poc-api-matias:latest .

      - name: Run Scan
        env:
          QUALYS_ACCESS_TOKEN: ${{ secrets.QUALYS_ACCESS_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./qualys_container_scan.sh
          ./qualys_container_scan.sh
